### ISSUE TITLE
Port forwarding issue

### ISSUE THREAD

**Issue by JeongChanwoo** [jolibrain/dd_platform_docker#10]
What should I change in the file when doing port forwarding?
In the file, only the nginx related content has the port setting.
When I modified the facade part with the port I want to configure, it doesn't work to be port forwarding.

And also, Jupiter errors also appear in the docker log contents. It is also restarting when nginx checks with docker ps.

**Comment by alx** [comment]
Hi @JeongChanwoo 

Port forwarding is defined in `docker-compose.yml` inside the `nginx` container options: https://github.com/jolibrain/dd_platform_docker/blob/master/code/gpu/docker-compose.yml#L54

```
...
  nginx:
   ...
    ports:
      - '1912:80'
```

By default, the frontal port is `1912`, so the platform is accessible on `http://localhost:1912`, you can modify it as you wish.

Then `nginx` container redirect requests to various containers inside the docker network in `nginx.conf` `upstream` config settings:

https://github.com/jolibrain/dd_platform_docker/blob/master/code/gpu/config/nginx/nginx.conf

Other platform containers are not accessible from outside docker by default. You'll need to add `port` config option for each container you want to access from outside in `docker-compose.yml` if needed.

Could you open another issue with your Jupyter errors and its related logs ?

Thanks,

Alex
