### ISSUE TITLE
DDPlatform: unable to access Predict services

### ISSUE THREAD

**Issue by vd3d** [jolibrain/dd_platform_docker#16]
Hi there,

I wish to fill an issue, here is a full description:

https://github.com/jolibrain/deepdetect/issues/766

PS: sorry to add the link, but it is to avoid double posting. But at the end, it should be discussed here.

**Comment by alx** [comment]
See update on jolibrain/deepdetect#766 issue, this issue should be fixed with latest `platform_ui` image.
