### ISSUE TITLE
Out of date dd_client.py installed by CPU image

### ISSUE THREAD

**Issue by eh-dub** [jolibrain/dd_platform_docker#27]
The version of `dd_client.py` that is installed with the CPU image is out of date. Specifically, it still uses the `async` keyword as a function parameter:
`def post_train(self, sname, data, parameters_input, parameters_mllib, parameters_output, async=True):`

I noticed that the version of `dd_client.py` on the [main repo](https://github.com/jolibrain/deepdetect/blob/master/clients/python/dd_client.py) has already been fixed.

**Comment by sileht** [comment]
The jupyter image now include an uptodate dd_client. But instead of using `dd_client.py` we should just load the system module. e.g.: `from dd_client import DD`
