### ISSUE TITLE
502 Bad Gateway Error when sending more than one image with dd_client.post_predict

### ISSUE THREAD

**Issue by eh-dub** [jolibrain/dd_platform_docker#29]
Everything behaves as expected when I send a single filename as shown below:
```
dd.post_predict(
        "text_detect_v2",
        data=[f],
        parameters_input={},
        parameters_mllib={},
        parameters_output={"confidence_threshold": 0.2, "bbox": True},
    )
```

But if I send an array of filenames, I get the following error:
`requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http://localhost:1912/api/deepdetect/predict`

Given that it's a 502 error, I suspect that there is an issue in `nginx.config` such that the proxy is not set up to recognize the shape of the response body for an array of images.

I'm running the `cpu` version.

**Comment by eh-dub** [comment]
I'm still getting a 502 when sending an array of filenames

**Comment by sileht** [comment]
Did you try to restart the container named cpu_platform_ui_1 after you ran update.sh ?

**Comment by eh-dub** [comment]
Apparently not. Merci!

**Comment by eh-dub** [comment]
I can send up to 17 images without getting a 502 Gateway response.
However, if I send 18 images, then I receive a 502 Gateway response.

The log of the `cpu_deepdetect` container printed:
```
Killed

DeepDetect [ commit 5e982df6b71b55e26715f71f304d534daa59dc7d ]
```
I also noticed that the `cpu_platform_data` container shut down.

I don't think it is the number of images so much as the amount of memory they take which is about 4 MB for my 18 images.

**Comment by beniz** [comment]
Yes this is due to the neural network maxing up your machine's memory when processing your batch of images. This the one of the few errors we can't do much about. Only true solution is increasing the RAM.

The `cpu_platform_data` container only transfers the platform data (models, test datasets, ...) once. When it's up to date, it shuts down almost immediately.
