### ISSUE TITLE
CPU Platform UI constantly makes request for GPU States

### ISSUE THREAD

**Issue by eh-dub** [jolibrain/dd_platform_docker#32]
I'm using the CPU container, which does not have a GPU. The Platform UI at localhost:1912 has a section that displays the GPU stats (figure 1). However, there are no GPU states which results in a constant stream of 404s (figure 2).
<img width="1792" alt="Screen Shot 2020-09-22 at 9 55 28 PM" src="https://user-images.githubusercontent.com/846035/93955830-abb78a00-fd1e-11ea-8a8e-d6872c6e3764.png">

<img width="860" alt="Screen Shot 2020-09-22 at 9 55 19 PM" src="https://user-images.githubusercontent.com/846035/93955782-875bad80-fd1e-11ea-809d-fbb41c54ab50.png">

Disregard the 502s for this issue.

**Comment by beniz** [comment]
Hi, you are correct the CPU platform should not ping GPU, and this may even free the right panel, cc @alx

**Comment by alx** [comment]
Hi @eh-dub 

Thanks for the feedback, `platform_ui` config file has been updated on `cpu` side to remove the default gpu monitoring.

`platform_ui` code is being updated to remove the right sidebar when no gpu are monitored.

**Comment by alx** [comment]
`platform_ui` fix is available in https://github.com/jolibrain/platform_ui/commit/44561429941a7c40b25092e14ce75f6040db43b3 and `jolibrain/platform_ui:dev` docker image
