### ISSUE TITLE
docker-compose.yml' is invalid

### ISSUE THREAD

**Issue by JeongChanwoo** [jolibrain/dd_platform_docker#8]
Hi
when i composed up docker.yml in gpu directory
this error is occur

ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.deepdetect: 'runtime'
Unsupported config option for services.gpustat_server: 'runtime'

I referenced this site(https://www.deepdetect.com/quickstart-platform/?os=ubuntu&source=docker&compute=gpu&gpu=gtx&backend=caffe%2Ctsne%2Cxgboost&deepdetect=platform)

**Comment by alx** [comment]
Hi @JeongChanwoo 

Which version of `docker-compose` are your using ?

```
$ docker-compose --version
docker-compose version 1.23.2, build unknown
```

> Version 2.3 files are supported by Compose 1.16.0+.
> 
> Introduces the following additional parameters:
> - `runtime`
https://docs.docker.com/compose/compose-file/compose-versioning/#version-23

**Comment by JeongChanwoo** [comment]
Thank you for your reply @alx 
In my case docker version is 1.8.0

**Comment by alx** [comment]
Thanks.

In this case, you need to upgrade to 1.16.0+ in order to use the `runtime: nvidia` config line from the `docker-compose.yml` file.
